apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-sweeper-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      role: container-sweeper-kube
  template:
    metadata:
      labels:
        role: container-sweeper-kube
    spec:
      containers:
      - name: container-sweeper-kube
        image: container-sweeper-kube:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
